[package]
edition = "2018"
name = "algorithm"
version = "0.1.0"

[[bin]]
name = "binary_search"
path = "leetcode/studyplan_algorithm1/binary_search/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
