CC=clang++

FLAGS=-std=c++2a -Wshadow -Wall -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -g -I/opt/homebrew/include -L/opt/homebrew/lib -lfmt -DFMT_ENABLED

day1:
	$(CC) $(FLAGS) day1.cpp

day2:
	$(CC) $(FLAGS) day2.cpp